# Generated by Django 4.2.3 on 2023-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0001_initial'),
        ('matakuliah', '0006_alter_matakuliah_nama_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='krs',
            field=models.ManyToManyField(related_name='mata_kuliah_set', to='krs.krs'),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Matematika Teknik', 'Matematika Teknik'), ('Sistem Informasi', 'Sistem Informasi'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Desain Web', 'Desain Web'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Struktur Data', 'Struktur Data')], max_length=100),
        ),
    ]
